language: python
python: 3.6
install:
  - pip install -r requirements.txt
  - bundle install
script:
  - src/bin/checkschema.py equipment src/config/equipment/*.yml
  - src/bin/checkschema.py ingredient src/config/ingredients/*.yml
  - src/bin/checkschema.py recipe src/config/recipes/**/*.yml
