language: python
python: 3.6
before_install:
  - sudo apt install --assume-yes make pandoc python3-pip
install:
  - pip3 install cerberus pyyaml
addons:
  apt:
    update: true
script:
  - src/bin/checkschema.py equipment src/config/equipment/*.yml
  - src/bin/checkschema.py ingredient src/config/ingredients/*.yml
  - src/bin/checkschema.py recipe src/config/recipes/*.yml
