id: 'aeropress-coffee'
name: 'AeroPress Coffee'
yield: 1
prep-time: '2 minutes'
cook-time: '1 minute'
equipment:
    - name: 'Burr Grinder'
      link: 'ref:coffee-grinder'
    - name: 'AeroPress'
      link: 'ref:coffee-makers'
    - name: 'Reuseable filter cap (highly recommended)'
      link: 'ref:coffee-makers'
    - name: 'Kitchen scale'
      link: 'ref:kitchen-scales'
    - name: 'Kettle'
      link: 'ref:kettles'
    - name: 'Water pitcher'
      link: 'ref:water-pitchers'
    - name: 'Thermometer'
      link: 'ref:thermometers'
    - name: 'Coffee Cup'
      link: 'ref:coffee-cups'
    - name: 'Stir Paddle'
      link: 'ref:coffee-makers'
ingredients:
    - name: 'Coffee beans'
      unit: 'grams'
      quantity: 15
    - name: 'Filtered water'
      unit: 'grams'
      quantity: 180
directions:
    - step: 'Place coffee cup on kitchen scale, then place AeroPress on coffee cup with plunger removed'
    - step: 'Put coffee beans inside hopper of burr grinder'
    - step: 'Set grinder to the finest level available, then grind beans'
    - step: 'Pour water from water pitcher into kettle'
    - step: 'Heat water, testing water temperature with thermometer until reaching [temp:92C] - [temp:95C]'
    - step: 'Turn on kitchen scale, setting weight to zero grams'
    - step: 'Pour coffee grounds into AeroPress, then hit Tare'
    - step: 'Pour water into AeroPress'
    - step: 'Carefully stir with stir paddle until grounds are fully submerged'
    - step: 'Move Aeropress off of kitchen scale onto countertop surface'
    - step: 'Put plunger onto AeroPress'
    - step: 'Wait one minute, then push plunger down until a hissing sound occurs'
