id: 'french-press-coffee'
name: 'French Press Coffee'
summary: test
yield: 1
prep-time: '1 minutes'
cook-time: '4 minutes'
equipment:
    - name: 'Burr Grinder'
      link: 'ref:coffee-grinder'
    - name: 'French Press'
      link: 'ref:french-presses'
    - name: 'Kettle'
      link: 'ref:kettles'
    - name: 'Water Pitcher'
      link: 'ref:water-pitchers'
    - name: 'Thermometer'
      link: 'ref:thermometers'
    - name: 'Coffee Cup'
      link: 'ref:coffee-cups'
    - name: 'Spoon'
ingredients:
    - name: 'Coffee beans'
      unit: 'grams'
      quantity: 15
    - name: 'Filtered water'
      unit: 'grams'
      quantity: 180
directions: 
    - step: 'Place coffee cup on kitchen scale, then place French Press on coffee cup with top removed'
    - step: 'Put coffee beans inside hopper of burr grinder'
    - step: 'Set grinder to the roughest level available, then grind beans'
    - step: 'Pour filtered water into kettle'
    - step: 'Heat water, testing water temperature with thermometer until reaching 92 - 95C (198 - 204F)'
    - step: 'Turn on kitchen scale, setting weight to zero grams'
    - step: 'Pour coffee grounds into French Press, then hit Tare'
    - step: 'Pour water into French Press, the until grounds are fully submerged'
    - step: 'Move French Press off of kitchen scale onto countertop surface'
    - step: 'Put plunger onto French Press'
    - step: 'Push plunger down until touching surface of water'
    - step: 'Wait four minutes before pushing plunger down'
    - step: 'Pour coffee into coffee cup'
