id: 'brownie-cookies'
name: 'Brownie Cookies'
yield: 30
prep-time: '75 minutes'
cook-time: '12 minutes'
equipment:
    - name: 'Whisk'
      link: 'ref:whisk'
    - name: 'Baking Sheet'
      link: 'ref:baking-sheet'
    - name: 'Microwave'
      link: 'ref:microwave'
    - name: 'Mixing Bowls'
      link: 'ref:mixing-bowls'
    - name: 'Sifter'
      link: 'ref:sifter'
    - name: 'Spatula'
      link: 'ref:spatula'
ingredients:
    - name: 'dark chocolate'
      unit: 'gram'
      quantity: 150
    - name: 'unsalted butter'
      unit: 'gram'
      quantity: 115
    - name: 'large eggs'
      quantity: 2
    - name: 'sugar'
      unit: 'gram'
      quantity: 55
    - name: 'brown sugar'
      unit: 'gram'
      quantity: 55
    - name: 'salt'
      unit: 'gram'
      quantity: 2
    - name: 'Nutella'
      unit: 'gram'
      quantity: 50
    - name: 'vanilla extract'
      unit: 'gram'
      quantity: 5
    - name: 'all purpose flour'
      unit: 'gram'
      quantity: 60
    - name: 'cake flour'
      unit: 'gram'
      quantity: 150
    - name: 'baking powder'
      unit: 'gram'
      quantity: 2
    - name: 'baking soda'
      unit: 'gram'
      quantity: 1
directions:
    - step: 'Combine 150 grams of dark chocolate and 40 grams of unsalted butter'
    - step: 'Microwave for thirty seconds than mix it'
    - step: 'In a different bowl, combine and whisk one egg, 55 grams of brown sugar and 1 gram of salt until foamy'
    - step: 'Add and whisk in the dark chocolate mixture'
    - step: 'Add 50 grams of Nutella and three grams of vanilla extract'
    - step: 'Sift than mix in 60 grams of all purpose flour, two grams of baking powder, and one gram of baking soda'
    - step: 'Wrap the choclate mixture than refigerate it for one hour'
    - step: 'In a different bowl whisk in 75 grams of softened butter with 55 grams of sugar and one gram of salt'
    - step: 'Whisk in one egg and 2 grams of vanilla extract'
    - step: 'Sift in 150 grams of cake flour than mix it with a spatula'
    - step: 'Wrap the mixture and refigerate it for one hour'
    - step: 'After refigerating the white mixture, divide it into about 7 grams'
    - step: 'Roll the chocolate mixture ito 10 grams bowl'
    - step: 'Flatten the divided white mixture and than add on top the chocolate ball'
    - step: 'Wrap the white mixture around the choclate ball'
    - step: 'Flatten the balls onto a nonstick or parchment paper baking sheet'
    - step: 'Bake at 160 celsius for 12 minutes'
