id: 'chocolate chip cookies'
name: 'Chocolate Chip Cookies'
yield: 16
prep-time: '20 minutes'
cook-time: '17 minutes'
equipment:
    - name: 'Whisk'
      link: 'ref:whisk'
    - name: 'Baking Sheet'
      link: 'ref:baking-sheet'
    - name: 'Mixing Bowls'
      link: 'ref:mixing-bowls'
    - name: 'Sifter'
      link: 'ref:sifter'
    - name: 'Spatula'
      link: 'ref:spatula'
    - name: 'Sauce Pan'
      link: 'ref:sauce-pan'
    - name: 'Kitchen Scale'
      link: 'ref:kitchen-scales'
    - name: 'Stove stop or hot plate'
ingredients:
    - name: 'all purpose flour'
      unit: 24 grams
    - name: 'baking soda'
      unit: 2 grams
    - name: 'unsalted butter'
      unit: 198.5 grams
    - name: 'dark brown sugar'
      unit: 165 grams
    - name: 'granulated sugar'
      unit: 100 grams
    - name: 'vanilla extract'
      unit: 3 grams
    - name: 'salt'
      unit: 4 grams
    - name: 'egg'
      quantity: 2
    - name: 'semisweet chocolate chips'
      unit: 106 grams
directions:
    - step: 'Adjust an oven rack to the middle'
    - step:  'Set the oven to 190 celsius'
    - step: 'Line two baking sheets with parchment paper'
    - step: 'In a mxing bowl, sift in 200 grams flour and baking soda'
    - step: 'In a 10 inch skillet melt 142 grams of butter'
    - step: 'Cook the butter for one to three minutes until it is golden brown'
    - step: 'Transfer the butter onto a large mixing bowl and stir in the rest of the butter until fully incorporated'
    - step: 'Whisk in brown sugar, granulated sugar, vanilla extract, and salt until it is incorporated'
    - step: 'Whisk in two eggs until no lumps remaining'
    - step: 'Using a rubber spatula mix in 24 grams or more flour until it is combined'
    - step: 'Add and mix in chocolate chips'
    - note: 'you may also add in nuts'
    - step: 'roll 42 grams of dough into a ball'
    - step: 'Line the balls of dough so that they are 5 centimeters apart from each other on the prepared baking sheets'
    - step: 'Bake for 10 to 14 minutes until it is golden brown'
