id: cucumber-martini
name: Cucumber Martini
yield: 1 serving
prep-time: 1 minute
cook-time: 3 minutes
equipment:
  - name: Bar Spoon
    link: ref:bar-spoons
  - name: Martini Glass
    link: ref:martini-glasses
  - name: Mixing Glass
    link: ref:mixing-glasses
  - name: Julep Strainer
    link: ref:julep-strainers
  - name: Kitchen Knife
ingredients:
  - name: Hendrick's Gin
    quantity: 2 ounces
    # TODO: Support notes for ingredients and equipment.
    # note: If choosing to substitute another gin, look for a flavour profile that incorporates citrus and cucumber notes.
  - name: Dry Vermouth
    quantity: 1 ounce
  - name: Grapefruit Bitters
    quantity: 1 milliliter
  - name: Grapefruit
    quantity: 1
  - name: English Cucumber
    quantity: 1
directions:
  - step: Place the martini glass into a freezer or icebox to chill.
  - step: Add the grapefruit bitters, dry vermouth, and gin to the mixing glass.
  - step: Fill mixing glass with crushed ice.
  - step: Use the bar spoon to stir the drink for about 30 seconds to 1 minute, depending on desired temperature and dilution.
    note:
      When stirring, allow the back of the spoon to follow the edge of the glass.
      The stirring action should be performed by the moving ice rather than by the bar spoon.
  - step: Use the julep strainer to pour the drink into the martini glass. Discard the ice.
  - step:
      Cut a long, thick peel from the grapefruit. Twist it over the drink to infuse the oils.
      Garnish the drink by balancing the peel along the edge of the glass.
  - step: Garnish the drink with a slice of cucumber, placed near to the grapefruit peel.
