id: 'orange-margarita'
name: 'Orange Margarita'
yield: 1
prep-time: '1 minute'
cook-time: '2 minutes'
equipment:
        - name: 'Kitchen Scale'
          link: 'ref:kitchen-scales'
        - name: 'Cocktail Shaker'
          link: 'ref:cocktail-shakers'
        - name: 'Martini Glass'
          link: 'ref:cocktail-glasses'
ingredients:
        - name: 'Tequila'
          unit: 'gram'
          quantity: 49
          link: 'ref:tequila'
        - name: 'Cointreau'
          unit: 'gram'
          quantity: 56
          link: 'ref:cointreau'
        - name: 'Coarse kosher salt'
          link: 'ref:kosher-salt'
          quantity: 25
directions:
        - step: 'Place cocktail shaker on kitchen scale'
        - step: 'Turn on kitchen scale and wait for it to set to zero with measurement set to grams'
        - step: 'Add crushed ice to cocktail shaker, then hit Tare'
        - step: 'Add liquid ingredients to cocktail shaker, hitting Tare between each addition'
        - step:  'Place lid on cocktail shaker, then hold firmly, and shake vigorously for about 10 seconds'
        - step: 'Pour cocktail into martini glass'
