id: 'sidecar'
name: 'Sidecar'
yield: 1
prep-time: '2 minutes'
cook-time: '2 minutes'
equipment:
        - name: 'Kitchen Scale'
          link: 'ref:kitchen-scales'
          name: 'Cocktail Shaker'
          link: 'ref:cocktail-shakers'
          name: 'Martini Glass'
          link: 'ref:cocktail-glasses'
ingredients:
        - name: 'Rémy Martin VSOP Cognac'
          quantity: 56 gram
          link: 'ref:cognac'
        - name: 'Cointreau'
          quantity: 52 gram
          link: 'ref:cointreau'
        - name: 'Fresh lemon juice'
          quantity: 40 grams
        - name: 'Simple Syrup'
          quantity: 20 grams
          link: 'ref:simple-syrup'
        - name: 'Crushed ice'
          quantity: 200 grams
        - name: 'Superfine sugar'
          link: 'ref:superfine-sugar'
          quantity: 25 grams
directions:
        - step: 'Invert martini glass and line rim with lemon juice'
        - step: 'Invert martini glass and line rim with superfine sugar'
        - step: 'Place cocktail shaker on kitchen scale'
        - step: 'Turn on kitchen scale and wait for it to set to zero with measurement set to grams'
        - step: 'Add crushed ice, then hit Tare'
        - step: 'Add liquid ingredients in no particular order, hitting Tare between each addition added'
        - step: 'Place lid on cocktail shaker, then shake vigorously for about 10 seconds'
        - step: 'Pour cocktail into martini glass'
