name: recipe name
yield: 1
prep-time: 1 minute
cook-time: 1 minute
equipment:
- name: equipment name
  link: equipment:link_id
ingredients:
- name: ingredient name
  quantity: 1 gram
  link: ingredient:link_id
directions:
- step: step
  note: optional note
tags:
- tag1
- tag2
